- name: Install nginx
  yum:
    name: nginx
    state: present
- name: Copy nginx configuration for Wordpress
  template:
   src: index.nginx-debian.html
   dest: /var/www/html/index.nginx-debian.html
   service:
    name: nginx
    state: restarted
